### ISSUE TITLE
Add no-multi-str to overrides config

### ISSUE THREAD

**Issue by cdfa** [rx-ts/eslint-mdx#27]
Due to https://github.com/mdx-js/mdx/issues/195, we can't use multi-line template strings in MDX (for use with `styled-components` for example). Therefore, I think we should disable `no-multi-str` in the `overrides` config.

**Comment by JounQin** [comment]
@cdfa But it does work without empty line:

```js
export default () => `<div>
content
</div>`
```

**Comment by cdfa** [comment]
Hmm, my apologies, it seems to be an issue with another package and not `mdx` in general.
