### ISSUE TITLE
Incompatibility with @typescript-eslint

### ISSUE THREAD

**Issue by Kerumen** [rx-ts/eslint-mdx#92]
When we use the config `@typescript-eslint/recommended-requiring-type-checking` from [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin) we have to set `parserOptions.project`.

It seems that `eslint-mdx` overwrites the `parserOptions.project` config because when we run `eslint` we get this error:

```
Error: Error while loading rule '@typescript-eslint/no-misused-promises': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
```

**Comment by JounQin** [comment]
Please provide more detail.

Including your eslint config, or a minimal runnable reproduction.

(This seems a usage question, instead of bug, IMO)

You can always use `overrides` feature of `eslint`, check https://github.com/1stG/configs/blob/master/packages/eslint-config/overrides.js as reference or demo.

**Comment by JounQin** [comment]
Don't enable `@typescript-eslint/recommended-requiring-type-checking` for all files.

**Comment by daviddelusenet** [comment]
I was also experiencing this issue, I solved it by doing the following:

- Removed `@typescript-eslint/recommended-requiring-type-checking` from my extends.
- Added the following part to the `overrides` section in my ESLint configuration:

```json
{
  "files": ["*.tsx"],
  "extends": ["plugin:@typescript-eslint/recommended-requiring-type-checking"]
}
```

The error went away and linting works fine!

**Comment by jackkrone** [comment]
> I was also experiencing this issue, I solved it by doing the following:
> 
>     * Removed `@typescript-eslint/recommended-requiring-type-checking` from my extends.
> 
>     * Added the following part to the `overrides` section in my ESLint configuration:
> 
> 
> ```json
> {
>   "files": ["*.tsx"],
>   "extends": ["plugin:@typescript-eslint/recommended-requiring-type-checking"]
> }
> ```
> 
> The error went away and linting works fine!

Could you share your full eslintrc setup? When I use your solution I get the same eslint error in all of my mdx files: `Parsing error: Expression expected`

**Comment by JounQin** [comment]
@jackkrone You'd better provide your reproduction instead.

**Comment by jackkrone** [comment]
@JounQin Sure. I just figured it out, as indicated in https://github.com/mdx-js/eslint-mdx/issues/251#issuecomment-963837780

This is what my `overrides` array looks like in eslintrc:
```
  "overrides": [
    {
      "files": [".tsx", ".ts"],
      "extends": "plugin:@typescript-eslint/recommended-requiring-type-checking"
    },
    {
      "files": ["*.mdx"],
      "extends": "plugin:mdx/recommended"
    }
  ]
```

I've found that this is required if using the `@typescript-eslint/parser` and the `@typescript-eslint/recommended-requiring-type-checking` plugin
